package com.skyros.ecommerce.entity;
// Generated Oct 15, 2020 2:41:51 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Product generated by Ahmed Baz
 */
@Entity
@Table(name = "product", schema = "public")
@Data
@NamedQuery(
        name = "product.findProduct",
        query = "select p  from Product p WHERE p.id=:id")
@NamedNativeQuery(
        name = "product.findProductNative",
        query = "select * from Product p  WHERE p.id=:id",
        resultClass = Product.class)
@AllArgsConstructor
@NoArgsConstructor
public class Product implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;
    private String sku;// Stock Keeping Unite
    private String name;
    private String description;
    @Column(name = "unit_price")
    private BigDecimal unitPrice;
    @Column(name = "image_url")
    private String imageUrl;
    @Column(name = "active")
    private Boolean active;
    @Column(name = "units_in_stock")
    private Integer unitsInStock;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_created", length = 29)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    private Date dateCreated;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_updated", length = 29)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    private Date lastUpdated;
}


